version: '3.9'
services:
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: hotel,comments
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      HOST_AUTH_METHOD: trust
    volumes:
      - ./dockerscripts:/docker-entrypoint-initdb.d